--ALUNOS:JOÃO JUNIOR E FABIO MANOEL TURMA: B

--CRIANDO BANCO DE DADOS DA ACÂDEMIA

CREATE DATABASE ACADEMIA

--CRIAÇÃO DA TABELA ALUNOS

CREATE TABLE ALUNOS (
   NOME VARCHAR(40),
   DATA_DE_NASCIMENTO DATE,
   BAIRRO VARCHAR(40),
   STATUS_DE_PAGAMENTO VARCHAR(50),
 );

 --CRIAÇÃO DA TABELA CHECK_INS
 CREATE TABLE CHECK_INS (
   NOME_DO_ALUNO VARCHAR(50),
   DATA_E_HORA_DE_ENTRADA DATETIME,
   VEZES_ENTRADA INT,
 );

--CRIAÇÃO DA TABELA COMPRAS
 CREATE TABLE COMPRAS (
   NOME_DO_ALUNO VARCHAR(50),
   PRODUTO VARCHAR(50),
   VALOR SMALLMONEY,
   DATA_DE_COMPRA DATETIME,
 );

-- CRIAÇÃO DA TABELA SUPLEMENTOS
CREATE TABLE SUPLEMENTOS (
    NOME_DO_PRODUTO VARCHAR(40),
	CATEGORIA VARCHAR(50),
	PRECO SMALLMONEY,
);
-- CRIAÇÃO DA TABELA BAIRRO
CREATE TABLE BAIRRO (  
     NOME_DO_BAIRRO VARCHAR(40),
     TOTAL_DE_ALUNOS TINYINT,
);
-- CRIAÇÃO DA TABELA RELATÓRIOS
CREATE TABLE RELATORIOS (
	ALUNO VARCHAR(40),
	TIPO_DE_RELATORIO VARCHAR(50),
	RESULTADO VARCHAR(50),
);
--INSERÇÃO NA TABELA COMPRAS
INSERT INTO COMPRAS (NOME_DO_ALUNO, PRODUTO, VALOR, DATA_DE_COMPRA)
VALUES ('John Marston', 'GH', 735.00, '2025-09-04T18:30:25'),
       ('Fabio Bundoviski', 'STRAPS', 17.99, '2025-12-25T19:30:10'),
	   ('Maju Toucinho', 'COQUETEIRA', 39.99, '2025-08-12T15:09:12'),
	   ('Luiz Bolsonaro da Silva', 'HALTERES', 488.39, '2025-12-25T19:30:10');

--INSERÇÃO NA TABELA ALUNOS
INSERT INTO ALUNOS (NOME, DATA_DE_NASCIMENTO, BAIRRO, STATUS_DE_PAGAMENTO)
VALUES ('John Marston', '1873-09-19', 'Centro', 'Pago' ),
        ('João Godofredo', '2007-09-18', 'Centro', 'Inadimplente'),
		('Fabio Bundoviski', '2005-08-13', 'Centro', 'Inadimplente' ),
		('Henry de Skalitz', '1380-03-22', 'Skalitz', 'Pago'),
		('Maju Toucinho', '1980-05-16', 'Santos', 'Pago' ),
		('Luiz Bolsonaro da Silva', '1955-10-27','Planalto Geral', 'Inadimplente');

--INSERÇÃO NA TABELA CHECK-INS
INSERT INTO CHECK_INS (NOME_DO_ALUNO, DATA_E_HORA_DE_ENTRADA, VEZES_ENTRADA)
 VALUES ('John Marston', '2025-09-25T17:30:25', 2),
        ('João Godofredo', '2025-12-25T19:30:10', 3),
		('Fabio Bundoviski', '2025-08-13T13:00:13', 1),
		('Henry de Skalitz', '2025-08-12T15:09:12', 4),
		('Maju Toucinho', '2025-07-20T17:00:29', 1),
		('Luiz Bolsonaro da Silva', '2025-12-25T17:00:14', 2);

--INSERÇÃO NA TABELA SUPLEMENTOS
INSERT INTO SUPLEMENTOS ( NOME_DO_PRODUTO, CATEGORIA, PRECO)
VALUES
('WEY PROTEIN', 'PROTEÍNA', 149.99),
('GH', 'BOMBA', 735.00),
('HALTERES', 'PESO', 488.39),
('STRAPS', 'ACESSÓRIO', 17.99),
('COQUETEIRA', 'ACESSÓRIO', 39.99);

--INSERÇÃO NA TABELA BAIRRO
INSERT INTO BAIRRO (NOME_DO_BAIRRO, TOTAL_DE_ALUNOS)
VALUES
('Centro', 3),
('Skalitz', 1),
('Santos', 1),
('Planalto Geral', 1);

--INSERÇÃO NA TABELA RELATÓRIOS
INSERT INTO RELATORIOS ( ALUNO, TIPO_DE_RELATORIO, RESULTADO)
VALUES
('João Godofredo', 'Massa Muscular', 'Aumento em 6kg de massa muscular'),
('Fabio Bundoviski', 'Força Muscular', 'Aumento em 3Kg em sua força maciça'),
('Henry de Skalitz', 'Corrida', 'Melhorou sua habilidade em agilidade em 5%'),
('Maju Toucinho', 'Redução de Gordura', 'Perdeu 5% de gordura corporal'),
('Luiz Bolsonaro da Silva', 'Flexibilidade', 'Aumento de 22cm no alongamento clavicular');

--RELATÓRIOS A SEREM GERADOS:
--CHECK-INS(por João jr)

SELECT 
    NOME_DO_ALUNO, 
    SUM(VEZES_ENTRADA) AS QUANTIDADE_CHECK_INS
FROM CHECK_INS
GROUP BY NOME_DO_ALUNO
ORDER BY QUANTIDADE_CHECK_INS DESC;

--ALUNOS INADIMPLENTES(por João jr)

SELECT * 
FROM ALUNOS
WHERE STATUS_DE_PAGAMENTO = 'Inadimplente';

--MÉDIA ANIVERSÁRIO(por João jr)

SELECT AVG(MONTH(DATA_DE_NASCIMENTO)) AS MEDIA_MES_ANIVERSARIO
FROM ALUNOS;

SELECT 
    NOME, 
    DATA_DE_NASCIMENTO, 
    MONTH(DATA_DE_NASCIMENTO) AS MES_NASCIMENTO,
    (SELECT AVG(MONTH(DATA_DE_NASCIMENTO)) FROM ALUNOS) AS MEDIA_MES_ANIVERSARIO
FROM ALUNOS;

--BAIRRO COM MAIS ALUNOS CADASTRADOS(por Fábio)
SELECT NOME_DO_BAIRRO, SUM(TOTAL_DE_ALUNOS) AS QUANTIDADE_ALUNOS
FROM BAIRRO
GROUP BY NOME_DO_BAIRRO;


--ALUNOS QUE MAIS COMPRARAM SUPLEMENTOS(por Fábio)
SELECT NOME_DO_ALUNO, SUM(VALOR) AS TOTAL_GASTO
FROM COMPRAS
GROUP BY NOME_DO_ALUNO
ORDER BY TOTAL_GASTO DESC;





--DROP DAS TABELAS
DROP TABLE ALUNOS
DROP TABLE CHECK_INS
DROP TABLE COMPRAS
DROP TABLE SUPLEMENTOS
DROP TABLE BAIRRO
DROP TABLE RELATORIOS

--TESTE DE SELEÇÃO
SELECT * FROM ALUNOS
SELECT * FROM CHECK_INS
SELECT * FROM COMPRAS
SELECT * FROM SUPLEMENTOS
SELECT * FROM BAIRRO
SELECT * FROM RELATORIOS